export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const from = await bookById(event, body?.fromBook)
  await requireBook(event, from.id)
  const to = await bookById(event, body?.toBook)
  if (to.group_id !== from.group_id || to.id === from.id) throw fail(400, 'Pick a friend in the same group')
  const give = cleanNos(body?.give)
  const get = cleanNos(body?.get)
  if (!give.length && !get.length) throw fail(400, 'Pick at least one sticker')
  let no = await missingSpare(event, from, give)
  if (no) throw fail(409, `${from.child_name} has no spare #${no} that isn't already promised`)
  no = await missingSpare(event, to, get)
  if (no) throw fail(409, `${to.child_name} has no spare #${no} that isn't already promised`)
  const id = crypto.randomUUID()
  const now = Date.now()
  await db(event).prepare(`INSERT INTO trades (id, group_id, from_book, to_book, give_json, get_json, status, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, 'offered', ?, ?)`).bind(id, from.group_id, from.id, to.id, JSON.stringify(give), JSON.stringify(get), now, now).run()
  return { id }
})
